"""add is_approved to doctors

Revision ID: 1f613aac38fc
Revises: 50279dbfe400
Create Date: 2026-05-28 11:25:58.176666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f613aac38fc'
down_revision: Union[str, None] = '50279dbfe400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.execute("UPDATE doctors SET is_approved = false WHERE is_approved IS NULL")
    op.alter_column('doctors', 'is_approved', nullable=False)
    op.add_column('doctors', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'approved_at')
    op.drop_column('doctors', 'is_approved')
    # ### end Alembic commands ###
