"""fix patient birth_date to date type

Revision ID: 5247371003f8
Revises: 1f613aac38fc
Create Date: 2026-05-28 14:24:52.823706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5247371003f8'
down_revision: Union[str, None] = '1f613aac38fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'birth_date',
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        postgresql_using='birth_date::date'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'birth_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
