"""add_medical_history_to_medical_records

Revision ID: 92fbb6626669
Revises: 4b64a155c52f
Create Date: 2026-06-08 12:09:36.058373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fbb6626669'
down_revision: Union[str, None] = '4b64a155c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('medical_history', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'medical_history')
    # ### end Alembic commands ###
